use std::{
    fs::{self, File},
    path::Path,
};

use tempfile::tempdir;

use crate::{
    file::write_all_at,
    format::PAGE_SIZE,
    model::{CachePriority, EntryKey},
    store::{
        ExtentStore, ExtentStoreOptions,
        index::INDEX_DIRECTORY,
        operation::InsertOutcome,
        pool::{DATA_FILE, SLOT_OWNER_FILE, STATE_FILE},
    },
};

fn options() -> ExtentStoreOptions {
    ExtentStoreOptions::default()
        .with_extent_size(PAGE_SIZE * 8)
        .with_index_write_buffer_size(PAGE_SIZE * 4)
        .with_index_cache_size(1024 * 1024)
        .with_checkpoint_changes(usize::MAX)
}

fn key(index: u64) -> EntryKey {
    let mut bytes = [index as u8; 24];
    bytes[16..].copy_from_slice(&index.to_le_bytes());
    EntryKey::new(bytes).unwrap()
}

fn unhex(input: &str) -> Vec<u8> {
    assert!(input.len().is_multiple_of(2));
    input
        .as_bytes()
        .chunks_exact(2)
        .map(|digits| {
            let digit = |byte| match byte {
                b'0'..=b'9' => byte - b'0',
                b'a'..=b'f' => byte - b'a' + 10,
                _ => panic!("fixture hex must be lowercase ASCII"),
            };
            digit(digits[0]) << 4 | digit(digits[1])
        })
        .collect()
}

fn put_u32(output: &mut [u8], offset: usize, value: u32) {
    output[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
}

fn put_u64(output: &mut [u8], offset: usize, value: u64) {
    output[offset..offset + 8].copy_from_slice(&value.to_le_bytes());
}

/// Bytes generated by the pre-V4 store before the fixture was frozen.
/// This deliberately does not call the production encoder or checksum implementation.
fn frozen_v3_allocator_state() -> Vec<u8> {
    const COPY_SIZE: usize = 4096;
    const EXTENTS: usize = 115;
    const ENTRY_SIZE: usize = 24;
    const HEADER_SIZE: usize = 64;

    let mut output = vec![0; COPY_SIZE * 2];
    for page in 0..2 {
        let base = page * COPY_SIZE;
        output[base..base + 8].copy_from_slice(b"SCSEGST1");
        put_u32(&mut output, base + 8, 3);
        put_u32(&mut output, base + 12, EXTENTS as u32);
        put_u32(&mut output, base + 16, 8);
        put_u32(&mut output, base + 20, PAGE_SIZE as u32);
        put_u64(&mut output, base + 24, (page + 1) as u64);
        put_u64(&mut output, base + 32, (page + 1) as u64);
        for current in 0..3 {
            put_u32(&mut output, base + 40 + current * 4, u32::MAX);
        }
        put_u32(&mut output, base + 52, 0);
        put_u64(&mut output, base + 56, (PAGE_SIZE * 8) as u64);
        for extent in 0..EXTENTS {
            put_u32(&mut output, base + HEADER_SIZE + extent * ENTRY_SIZE, 1);
        }
        output[base + HEADER_SIZE + 17] = 1;
    }

    // The durable page records one high-priority entry in extent 1.
    let durable = COPY_SIZE;
    put_u32(&mut output, durable + 48, 1);
    let extent = durable + HEADER_SIZE + ENTRY_SIZE;
    put_u32(&mut output, extent + 4, 1);
    put_u64(&mut output, extent + 8, 1);
    output[extent + 16] = 2;
    output[extent + 17] = 2;

    output[COPY_SIZE - 4..COPY_SIZE].copy_from_slice(&[0xe1, 0x87, 0xcf, 0xf9]);
    output[COPY_SIZE * 2 - 4..COPY_SIZE * 2].copy_from_slice(&[0x42, 0x0c, 0x5e, 0xe1]);
    output
}

fn install_v3_fixture(root: &Path) {
    const DATA_LEN: u64 = 3_768_320;
    const OWNER_LEN: u64 = 58_880;
    const DATA_OFFSET: u64 = 32_768;
    const OWNER_OFFSET: u64 = 512;

    fs::create_dir_all(root.join(INDEX_DIRECTORY)).unwrap();
    let data = File::create(root.join(DATA_FILE)).unwrap();
    data.set_len(DATA_LEN).unwrap();
    write_all_at(
        &data,
        &unhex(
            "5343424c01000d001300000000000000636f6d7061742d6b65792d7633\
             66726f7a656e20657874656e742076616c7565",
        ),
        DATA_OFFSET,
    )
    .unwrap();
    let owners = File::create(root.join(SLOT_OWNER_FILE)).unwrap();
    owners.set_len(OWNER_LEN).unwrap();
    write_all_at(
        &owners,
        &unhex(
            "53434f570302000017782731cd06ed228776716adac218f92888fb936a627ff8\
             0100000030000000e32901140100000000000000130000001d5061d700000000",
        ),
        OWNER_OFFSET,
    )
    .unwrap();
    fs::write(root.join(STATE_FILE), frozen_v3_allocator_state()).unwrap();
    fs::write(
        root.join(INDEX_DIRECTORY).join("MANIFEST-1"),
        unhex(
            "46584c534d4d3031010000006000000001000000000000000000000000000000\
             0100000000000000010000000000000007000000000000001800000020000000\
             4000000000200000000000000000000000000000000000000000000000000000\
             fd02ae67",
        ),
    )
    .unwrap();
    fs::write(
        root.join(INDEX_DIRECTORY).join("wal-00000000000000000001.log"),
        unhex(
            "46584c534d573032020000000100000001000000000000000100000000000000\
             0000000000000000681dfa23d7acf20c17782731cd06ed228776716adac218f92\
             888fb936a627ff853434c4f0302000008000000000000000100000030000000e3\
             2901144b9dfb790100000000000000",
        ),
    )
    .unwrap();
}

#[test]
fn opens_and_advances_the_frozen_v3_store_fixture() {
    let dir = tempdir().unwrap();
    install_v3_fixture(dir.path());
    let fixture_key = EntryKey::new(b"compat-key-v3").unwrap();
    let fixture_value = b"frozen extent value";

    let store = ExtentStore::open_with_options(dir.path(), options()).unwrap();
    let loaded = store.get_with_stats(&fixture_key).unwrap();
    assert_eq!(loaded.value.as_deref(), Some(fixture_value.as_slice()));
    assert_eq!(loaded.priority, Some(CachePriority::High));
    let next_key = key(99);
    assert_eq!(
        store
            .insert(&next_key, b"written by current store", CachePriority::Normal)
            .unwrap(),
        InsertOutcome::Inserted
    );
    store.sync().unwrap();
    drop(store);

    let reopened = ExtentStore::open_with_options(dir.path(), options()).unwrap();
    assert_eq!(
        reopened.get(&fixture_key).unwrap().as_deref(),
        Some(fixture_value.as_slice())
    );
    assert_eq!(
        reopened.get(&next_key).unwrap().as_deref(),
        Some(b"written by current store".as_slice())
    );
}
